name: Docker build and push
 
on:
  push:
    branches:
      - main 
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/dependabot-auto-merge.yml'
      - '.github/workflows/dependabot-auto-merge.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/dependabot-auto-merge.yml'
      - '.github/workflows/dependabot-auto-merge.yml'
  schedule:
    - cron:  '0 0 * * 2'

  workflow_dispatch:

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        ignore: DL3008

    - name: "Build ${{ matrix.versions.tag }}"
      if: github.event_name == 'pull_request'
      uses: docker/build-push-action@v4
      with:
        push: false
        pull: true
        tags: ghcr.io/poad/amplify-custom-image
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: "Build and push ${{ matrix.versions.tag }}"
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v4
      with:
        push: true
        pull: true
        tags: ghcr.io/poad/amplify-custom-image
        build-args: |
          BUILDKIT_INLINE_CACHE=1

